// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "lapse_ui_scene.hpp"

namespace djinni_generated {

class NativeLapseUiScene final : ::djinni::JniEnum {
public:
    using CppType = ::lpase::LapseUiScene;
    using JniType = jobject;

    using Boxed = NativeLapseUiScene;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeLapseUiScene>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeLapseUiScene>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeLapseUiScene() : JniEnum("dyno/fun/lapse/LapseUiScene") {}
    friend ::djinni::JniClass<NativeLapseUiScene>;
};

}  // namespace djinni_generated
