// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "publish_channel.hpp"

namespace djinni_generated {

class NativePublishChannel final : ::djinni::JniEnum {
public:
    using CppType = ::lpase::PublishChannel;
    using JniType = jobject;

    using Boxed = NativePublishChannel;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativePublishChannel>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativePublishChannel>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativePublishChannel() : JniEnum("dyno/fun/lapse/PublishChannel") {}
    friend ::djinni::JniClass<NativePublishChannel>;
};

}  // namespace djinni_generated
