// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "project_list_gen.hpp"

namespace djinni_generated {

class NativeProjectListGen final : ::djinni::JniInterface<::lpase::ProjectListGen, NativeProjectListGen> {
public:
    using CppType = std::shared_ptr<::lpase::ProjectListGen>;
    using CppOptType = std::shared_ptr<::lpase::ProjectListGen>;
    using JniType = jobject;

    using Boxed = NativeProjectListGen;

    ~NativeProjectListGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeProjectListGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeProjectListGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeProjectListGen();
    friend ::djinni::JniClass<NativeProjectListGen>;
    friend ::djinni::JniInterface<::lpase::ProjectListGen, NativeProjectListGen>;

};

}  // namespace djinni_generated
