// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "moive_info_manager_gen.hpp"

namespace djinni_generated {

class NativeMoiveInfoManagerGen final : ::djinni::JniInterface<::lpase::MoiveInfoManagerGen, NativeMoiveInfoManagerGen> {
public:
    using CppType = std::shared_ptr<::lpase::MoiveInfoManagerGen>;
    using CppOptType = std::shared_ptr<::lpase::MoiveInfoManagerGen>;
    using JniType = jobject;

    using Boxed = NativeMoiveInfoManagerGen;

    ~NativeMoiveInfoManagerGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMoiveInfoManagerGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMoiveInfoManagerGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMoiveInfoManagerGen();
    friend ::djinni::JniClass<NativeMoiveInfoManagerGen>;
    friend ::djinni::JniInterface<::lpase::MoiveInfoManagerGen, NativeMoiveInfoManagerGen>;

};

}  // namespace djinni_generated
