// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "lapse_setting_gen.hpp"

namespace djinni_generated {

class NativeLapseSettingGen final : ::djinni::JniInterface<::lpase::LapseSettingGen, NativeLapseSettingGen> {
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingGen>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingGen>;
    using JniType = jobject;

    using Boxed = NativeLapseSettingGen;

    ~NativeLapseSettingGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLapseSettingGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLapseSettingGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLapseSettingGen();
    friend ::djinni::JniClass<NativeLapseSettingGen>;
    friend ::djinni::JniInterface<::lpase::LapseSettingGen, NativeLapseSettingGen>;

};

}  // namespace djinni_generated
