// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "lapse_event.hpp"

namespace djinni_generated {

class NativeLapseEvent final : ::djinni::JniEnum {
public:
    using CppType = ::lpase::LapseEvent;
    using JniType = jobject;

    using Boxed = NativeLapseEvent;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeLapseEvent>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeLapseEvent>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeLapseEvent() : JniEnum("dyno/fun/lapse/LapseEvent") {}
    friend ::djinni::JniClass<NativeLapseEvent>;
};

}  // namespace djinni_generated
