// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "quick_mode_gen.hpp"

namespace djinni_generated {

class NativeQuickModeGen final : ::djinni::JniInterface<::lpase::QuickModeGen, NativeQuickModeGen> {
public:
    using CppType = std::shared_ptr<::lpase::QuickModeGen>;
    using CppOptType = std::shared_ptr<::lpase::QuickModeGen>;
    using JniType = jobject;

    using Boxed = NativeQuickModeGen;

    ~NativeQuickModeGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeQuickModeGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeQuickModeGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeQuickModeGen();
    friend ::djinni::JniClass<NativeQuickModeGen>;
    friend ::djinni::JniInterface<::lpase::QuickModeGen, NativeQuickModeGen>;

};

}  // namespace djinni_generated
