// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "moive_info_gen.hpp"

namespace djinni_generated {

class NativeMoiveInfoGen final : ::djinni::JniInterface<::lpase::MoiveInfoGen, NativeMoiveInfoGen> {
public:
    using CppType = std::shared_ptr<::lpase::MoiveInfoGen>;
    using CppOptType = std::shared_ptr<::lpase::MoiveInfoGen>;
    using JniType = jobject;

    using Boxed = NativeMoiveInfoGen;

    ~NativeMoiveInfoGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMoiveInfoGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMoiveInfoGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMoiveInfoGen();
    friend ::djinni::JniClass<NativeMoiveInfoGen>;
    friend ::djinni::JniInterface<::lpase::MoiveInfoGen, NativeMoiveInfoGen>;

};

}  // namespace djinni_generated
