// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "lapse_setting_dlg_gen.hpp"

namespace djinni_generated {

class NativeLapseSettingDlgGen final : ::djinni::JniInterface<::lpase::LapseSettingDlgGen, NativeLapseSettingDlgGen> {
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingDlgGen>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingDlgGen>;
    using JniType = jobject;

    using Boxed = NativeLapseSettingDlgGen;

    ~NativeLapseSettingDlgGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLapseSettingDlgGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLapseSettingDlgGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLapseSettingDlgGen();
    friend ::djinni::JniClass<NativeLapseSettingDlgGen>;
    friend ::djinni::JniInterface<::lpase::LapseSettingDlgGen, NativeLapseSettingDlgGen>;

};

}  // namespace djinni_generated
