// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "data_gen.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDataGen final : ::djinni::JniInterface<::lpase::DataGen, NativeDataGen> {
public:
    using CppType = std::shared_ptr<::lpase::DataGen>;
    using CppOptType = std::shared_ptr<::lpase::DataGen>;
    using JniType = jobject;

    using Boxed = NativeDataGen;

    ~NativeDataGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDataGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDataGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDataGen();
    friend ::djinni::JniClass<NativeDataGen>;
    friend ::djinni::JniInterface<::lpase::DataGen, NativeDataGen>;

};

}  // namespace djinni_generated
