// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "interval_mode.hpp"

namespace djinni_generated {

class NativeIntervalMode final : ::djinni::JniEnum {
public:
    using CppType = ::lpase::IntervalMode;
    using JniType = jobject;

    using Boxed = NativeIntervalMode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeIntervalMode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeIntervalMode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeIntervalMode() : JniEnum("dyno/fun/lapse/IntervalMode") {}
    friend ::djinni::JniClass<NativeIntervalMode>;
};

}  // namespace djinni_generated
