// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "const_define.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConstDefine final {
public:
    using CppType = ::lpase::ConstDefine;
    using JniType = jobject;

    using Boxed = NativeConstDefine;

    ~NativeConstDefine();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeConstDefine();
    friend ::djinni::JniClass<NativeConstDefine>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/lapse/ConstDefine") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
