// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "logic_gen.hpp"

namespace djinni_generated {

class NativeLogicGen final : ::djinni::JniInterface<::lpase::LogicGen, NativeLogicGen> {
public:
    using CppType = std::shared_ptr<::lpase::LogicGen>;
    using CppOptType = std::shared_ptr<::lpase::LogicGen>;
    using JniType = jobject;

    using Boxed = NativeLogicGen;

    ~NativeLogicGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLogicGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLogicGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLogicGen();
    friend ::djinni::JniClass<NativeLogicGen>;
    friend ::djinni::JniInterface<::lpase::LogicGen, NativeLogicGen>;

};

}  // namespace djinni_generated
