// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "capture_quick_mode.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCaptureQuickMode final {
public:
    using CppType = ::lpase::CaptureQuickMode;
    using JniType = jobject;

    using Boxed = NativeCaptureQuickMode;

    ~NativeCaptureQuickMode();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeCaptureQuickMode();
    friend ::djinni::JniClass<NativeCaptureQuickMode>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/lapse/CaptureQuickMode") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
