// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include "djinni_support.hpp"
#include "project_cell_gen.hpp"

namespace djinni_generated {

class NativeProjectCellGen final : ::djinni::JniInterface<::lpase::ProjectCellGen, NativeProjectCellGen> {
public:
    using CppType = std::shared_ptr<::lpase::ProjectCellGen>;
    using CppOptType = std::shared_ptr<::lpase::ProjectCellGen>;
    using JniType = jobject;

    using Boxed = NativeProjectCellGen;

    ~NativeProjectCellGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeProjectCellGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeProjectCellGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeProjectCellGen();
    friend ::djinni::JniClass<NativeProjectCellGen>;
    friend ::djinni::JniInterface<::lpase::ProjectCellGen, NativeProjectCellGen>;

};

}  // namespace djinni_generated
