// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAConfigKeyValue.h"
#include "config_key_value.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPAConfigKeyValue;

namespace djinni_generated {

struct ConfigKeyValue
{
    using CppType = ::lpase::ConfigKeyValue;
    using ObjcType = LPAConfigKeyValue*;

    using Boxed = ConfigKeyValue;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
