// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>

@interface LPACaptureQuickMode : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)captureQuickMode;

@end

extern NSString * __nonnull const LPACaptureQuickModeTRAFFICFLOW;
extern NSString * __nonnull const LPACaptureQuickModeWINDSKY;
extern NSString * __nonnull const LPACaptureQuickModeSUNRISESET;
extern NSString * __nonnull const LPACaptureQuickModeNOWINDSKY;
extern NSString * __nonnull const LPACaptureQuickModeFLOWERSBLOOMFADE;
extern NSString * __nonnull const LPACaptureQuickModeDAYTURNNIGHT;
