// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPACaptureQuickMode.h"
#include "capture_quick_mode.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPACaptureQuickMode;

namespace djinni_generated {

struct CaptureQuickMode
{
    using CppType = ::lpase::CaptureQuickMode;
    using ObjcType = LPACaptureQuickMode*;

    using Boxed = CaptureQuickMode;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
