// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAConstDefine.h"


NSString * __nonnull const LPAConstDefineFLASH = @"flash";

NSString * __nonnull const LPAConstDefineAUTO = @"auto";

NSString * __nonnull const LPAConstDefineSTRYES = @"yes";

NSString * __nonnull const LPAConstDefineSTRNO = @"no";

NSString * __nonnull const LPAConstDefineQUALITY = @"quality";

NSString * __nonnull const LPAConstDefineQUALITYLOW = @"low";

NSString * __nonnull const LPAConstDefineQUALITYMEDIUM = @"medium";

NSString * __nonnull const LPAConstDefineQUALITYHIGH = @"high";

NSString * __nonnull const LPAConstDefineQUALITYPHOTO = @"photo";

NSString * __nonnull const LPAConstDefineCAMERAPOS = @"camera_pos";

NSString * __nonnull const LPAConstDefineCAMERAPOSFRONT = @"front";

NSString * __nonnull const LPAConstDefineCAMERAPOSBACK = @"back";

NSString * __nonnull const LPAConstDefineEXPOSURE = @"exposure";

NSString * __nonnull const LPAConstDefineMANUAL = @"manual";

NSString * __nonnull const LPAConstDefinePOINT = @"point";

NSString * __nonnull const LPAConstDefineEXPOSUREX = @"exposure_x";

NSString * __nonnull const LPAConstDefineEXPOSUREY = @"exposure_y";

NSString * __nonnull const LPAConstDefineEXPOSURELEV = @"exposure_lev";

NSString * __nonnull const LPAConstDefineISO = @"iso";

NSString * __nonnull const LPAConstDefineFOCUS = @"focus";

NSString * __nonnull const LPAConstDefineFOCUSRANGE = @"focus_range";

NSString * __nonnull const LPAConstDefineLOCK = @"lock";

NSString * __nonnull const LPAConstDefineINTERVAL = @"interval";

NSString * __nonnull const LPAConstDefineRESOLUTION = @"resolution";

NSString * __nonnull const LPAConstDefineFPS = @"fps";

NSString * __nonnull const LPAConstDefineBITRATE = @"bitrate";

@implementation LPAConstDefine

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)constDefine
{
    return [[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
