// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAConstDefine+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ConstDefine::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    (void)obj; // Suppress warnings in relase builds for empty records
    return {};
}

auto ConstDefine::fromCpp(const CppType& cpp) -> ObjcType
{
    (void)cpp; // Suppress warnings in relase builds for empty records
    return [[LPAConstDefine alloc] init];
}

}  // namespace djinni_generated
