// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>

@interface LPAConstDefine : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)constDefine;

@end

/** camera */
extern NSString * __nonnull const LPAConstDefineFLASH;
extern NSString * __nonnull const LPAConstDefineAUTO;
extern NSString * __nonnull const LPAConstDefineSTRYES;
extern NSString * __nonnull const LPAConstDefineSTRNO;
extern NSString * __nonnull const LPAConstDefineQUALITY;
extern NSString * __nonnull const LPAConstDefineQUALITYLOW;
extern NSString * __nonnull const LPAConstDefineQUALITYMEDIUM;
extern NSString * __nonnull const LPAConstDefineQUALITYHIGH;
extern NSString * __nonnull const LPAConstDefineQUALITYPHOTO;
extern NSString * __nonnull const LPAConstDefineCAMERAPOS;
extern NSString * __nonnull const LPAConstDefineCAMERAPOSFRONT;
extern NSString * __nonnull const LPAConstDefineCAMERAPOSBACK;
extern NSString * __nonnull const LPAConstDefineEXPOSURE;
extern NSString * __nonnull const LPAConstDefineMANUAL;
extern NSString * __nonnull const LPAConstDefinePOINT;
extern NSString * __nonnull const LPAConstDefineEXPOSUREX;
extern NSString * __nonnull const LPAConstDefineEXPOSUREY;
extern NSString * __nonnull const LPAConstDefineEXPOSURELEV;
extern NSString * __nonnull const LPAConstDefineISO;
extern NSString * __nonnull const LPAConstDefineFOCUS;
extern NSString * __nonnull const LPAConstDefineFOCUSRANGE;
extern NSString * __nonnull const LPAConstDefineLOCK;
/**video */
extern NSString * __nonnull const LPAConstDefineINTERVAL;
extern NSString * __nonnull const LPAConstDefineRESOLUTION;
extern NSString * __nonnull const LPAConstDefineFPS;
extern NSString * __nonnull const LPAConstDefineBITRATE;
