// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAConstDefine.h"
#include "const_define.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPAConstDefine;

namespace djinni_generated {

struct ConstDefine
{
    using CppType = ::lpase::ConstDefine;
    using ObjcType = LPAConstDefine*;

    using Boxed = ConstDefine;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
