// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPACaptureQuickMode.h"


NSString * __nonnull const LPACaptureQuickModeTRAFFICFLOW = @"traffic_flow";

NSString * __nonnull const LPACaptureQuickModeWINDSKY = @"wind_sky";

NSString * __nonnull const LPACaptureQuickModeSUNRISESET = @"sun_rise_set";

NSString * __nonnull const LPACaptureQuickModeNOWINDSKY = @"no_wind_sky";

NSString * __nonnull const LPACaptureQuickModeFLOWERSBLOOMFADE = @"flowers_bloom_fade";

NSString * __nonnull const LPACaptureQuickModeDAYTURNNIGHT = @"day_turn_night";

@implementation LPACaptureQuickMode

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)captureQuickMode
{
    return [[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
