// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>

@interface LPAConfigKeyValue : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)configKeyValue;

@end

extern NSString * __nonnull const LPAConfigKeyValueVIDEOINTERVAL;
extern NSString * __nonnull const LPAConfigKeyValueVIDEOINTERVALUNIT;
extern NSString * __nonnull const LPAConfigKeyValueVIDEOFPS;
extern NSString * __nonnull const LPAConfigKeyValueVIDEOBITRATE;
extern NSString * __nonnull const LPAConfigKeyValueCAPTUREMODE;
extern NSString * __nonnull const LPAConfigKeyValueCAPTUREMODEVIDEO;
extern NSString * __nonnull const LPAConfigKeyValueCAPTUREMODEPHOTO;
extern NSString * __nonnull const LPAConfigKeyValueCAPTUREMODELINE;
extern NSString * __nonnull const LPAConfigKeyValueCAPTUREIMMEDIATELINE;
