// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAConfigKeyValue.h"


NSString * __nonnull const LPAConfigKeyValueVIDEOINTERVAL = @"interval";

NSString * __nonnull const LPAConfigKeyValueVIDEOINTERVALUNIT = @"interval_unit";

NSString * __nonnull const LPAConfigKeyValueVIDEOFPS = @"fps";

NSString * __nonnull const LPAConfigKeyValueVIDEOBITRATE = @"video_bitrate";

NSString * __nonnull const LPAConfigKeyValueCAPTUREMODE = @"capture_mode";

NSString * __nonnull const LPAConfigKeyValueCAPTUREMODEVIDEO = @"video";

NSString * __nonnull const LPAConfigKeyValueCAPTUREMODEPHOTO = @"photo";

NSString * __nonnull const LPAConfigKeyValueCAPTUREMODELINE = @"capture_video_line";

@implementation LPAConfigKeyValue

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)configKeyValue
{
    return [[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
