// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>
@class LPADataGen;


@interface LPADataGen : NSObject

+ (nullable LPADataGen *)instance;

- (BOOL)initialize:(nonnull NSString *)config;

- (nonnull NSString *)getProjectsDir;

- (nonnull NSString *)getCaptureMode;

- (void)setCaptureMode:(nonnull NSString *)mode;

- (int32_t)getCaptureIntevalMillsec;

- (int32_t)getCaptureInteval;

- (nonnull NSString *)getCaptureIntevalUnit;

- (void)setCaptureInteval:(int32_t)value
                     unit:(nonnull NSString *)unit;

- (void)setCaptureIntervalQuickMode:(nonnull NSString *)mode;

- (nonnull NSString *)getCaptureIntervalQuickMode;

- (int32_t)getFps;

- (int32_t)getBitrate;

- (int32_t)getResolution;

- (void)setFps:(int32_t)fps;

- (void)setBitrate:(int32_t)bitrate;

- (void)setResolution:(int32_t)reso;

- (BOOL)isCaptureModePhoto:(int32_t)interal;

@end
