// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "lapse_setting_dlg_delegate.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol LPALapseSettingDlgDelegate;

namespace djinni_generated {

class LapseSettingDlgDelegate
{
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingDlgDelegate>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingDlgDelegate>;
    using ObjcType = id<LPALapseSettingDlgDelegate>;

    using Boxed = LapseSettingDlgDelegate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

