// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "lapse_setting_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPALapseSettingGen;

namespace djinni_generated {

class LapseSettingGen
{
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingGen>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingGen>;
    using ObjcType = LPALapseSettingGen*;

    using Boxed = LapseSettingGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

