// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "logic_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPALogicGen;

namespace djinni_generated {

class LogicGen
{
public:
    using CppType = std::shared_ptr<::lpase::LogicGen>;
    using CppOptType = std::shared_ptr<::lpase::LogicGen>;
    using ObjcType = LPALogicGen*;

    using Boxed = LogicGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

