// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "lapse_setting_ui_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol LPALapseSettingUiGen;

namespace djinni_generated {

class LapseSettingUiGen
{
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingUiGen>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingUiGen>;
    using ObjcType = id<LPALapseSettingUiGen>;

    using Boxed = LapseSettingUiGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

