// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>
@class LPALapseSettingGen;
@protocol LPALapseSettingUiGen;


@interface LPALapseSettingGen : NSObject

+ (nullable LPALapseSettingGen *)instance;

- (int32_t)getQuickModeCount;

- (nonnull NSString *)getQuickModeName:(int32_t)index;

- (void)selectQuickMode:(int32_t)index;

- (void)setFps:(int32_t)fps;

- (void)setLapse:(int32_t)lapse;

- (void)onLoad:(nullable id<LPALapseSettingUiGen>)ui;

- (void)onShow;

- (void)onHide;

- (void)clean;

@end
