// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "lapse_setting_dlg_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPALapseSettingDlgGen;

namespace djinni_generated {

class LapseSettingDlgGen
{
public:
    using CppType = std::shared_ptr<::lpase::LapseSettingDlgGen>;
    using CppOptType = std::shared_ptr<::lpase::LapseSettingDlgGen>;
    using ObjcType = LPALapseSettingDlgGen*;

    using Boxed = LapseSettingDlgGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

