// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, LPALapseEvent)
{
    LPALapseEventNone,
    LPALapseEventCameraBtnCapture,
    LPALapseEventCameraBtnPause,
    LPALapseEventCameraBtnStop,
    LPALapseEventCameraBtnResume,
    LPALapseEventCameraBtnLapse,
    LPALapseEventCameraBtnRatio,
    LPALapseEventCameraBtnMore,
    LPALapseEventCameraBtnLibrary,
    LPALapseEventCameraBtnSwitch,
    LPALapseEventMax,
};
