// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>


@protocol LPALapseSettingUiGen

- (void)initializeSliberFps:(int32_t)min
                        max:(int32_t)max;

- (void)initializeSliberLapse:(int32_t)min
                          max:(int32_t)max;

- (void)updateFps:(int32_t)fps;

- (void)updateLapse:(int32_t)lapse;

- (void)updatePicker:(int32_t)index;

@end
