// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAIntervalMode.h"
#import <Foundation/Foundation.h>
@class LPALapseSettingDlgGen;
@protocol LPALapseSettingDlgDelegate;


@interface LPALapseSettingDlgGen : NSObject

+ (nullable LPALapseSettingDlgGen *)instance;

- (void)onLoad:(nullable id<LPALapseSettingDlgDelegate>)delegate;

- (void)onShow;

- (BOOL)onFpsChange:(int32_t)fps;

- (BOOL)onLapseChange:(LPAIntervalMode)mode
                lapse:(float)lapse;

- (void)onSelectInterval:(LPAIntervalMode)mode;

- (BOOL)onSave:(int32_t)fps
         lapse:(float)lapse
          mode:(LPAIntervalMode)mode;

@end
