// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>
@class LPALogicGen;


@interface LPALogicGen : NSObject

+ (nullable LPALogicGen *)instance;

- (BOOL)initialize:(nonnull NSString *)config;

@end
