// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>


@interface LPAMoiveInfoGen : NSObject

- (nonnull NSString *)getName;

- (int32_t)getFrameAmount;

- (float)getDurationSecond;

- (float)getFPS;

- (float)getRecordLapse;

- (float)getRecordDuration;

- (BOOL)setName:(nonnull NSString *)name;

- (void)setFrameAmount:(int32_t)amount;

- (void)setDurationSecond:(float)seconds;

- (void)setFPS:(float)fps;

- (void)setRecordDuration:(float)duration;

- (void)setRecordLapse:(float)lapse;

@end
