// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAPublishChannel.h"
#import <Foundation/Foundation.h>
@class LPAProjectCellGen;
@class LPAProjectListGen;


@interface LPAProjectListGen : NSObject

+ (nullable LPAProjectListGen *)instance;

- (BOOL)load:(int32_t)reviewW
     reviewH:(int32_t)reviewH;

- (int32_t)getProjectAmount;

- (nullable LPAProjectCellGen *)getProjectData:(int32_t)index;

- (void)selectProject:(int32_t)index;

- (void)deleteProject:(int32_t)index;

- (void)publishProject:(int32_t)index
               channel:(LPAPublishChannel)channel;

- (void)saveProject:(int32_t)index;

- (void)watchProject:(int32_t)index;

@end
