// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "quick_mode_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPAQuickModeGen;

namespace djinni_generated {

class QuickModeGen
{
public:
    using CppType = std::shared_ptr<::lpase::QuickModeGen>;
    using CppOptType = std::shared_ptr<::lpase::QuickModeGen>;
    using ObjcType = LPAQuickModeGen*;

    using Boxed = QuickModeGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

