// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>
@class LPAQuickModeGen;


@interface LPAQuickModeGen : NSObject

+ (nullable LPAQuickModeGen *)create:(nonnull NSString *)name
                                 fps:(int32_t)fps
                            interval:(int32_t)interval;

- (nonnull NSString *)getName;

- (int32_t)getFps;

- (int32_t)getInterval;

@end
