// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPALapseEvent.h"
#import "LPALapseUiScene.h"
#import <Foundation/Foundation.h>
@class LPAUilogicGen;


@interface LPAUilogicGen : NSObject

+ (nullable LPAUilogicGen *)instance;

- (BOOL)initialize:(LPALapseUiScene)scene;

- (nonnull NSString *)getEventStr:(LPALapseEvent)event;

@end
