// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAVideoInfo.h"
#include "video_info.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LPAVideoInfo;

namespace djinni_generated {

struct VideoInfo
{
    using CppType = ::lpase::VideoInfo;
    using ObjcType = LPAVideoInfo*;

    using Boxed = VideoInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
