// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAVideoInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto VideoInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.interval),
            ::djinni::I32::toCpp(obj.fps),
            ::djinni::I32::toCpp(obj.resolution),
            ::djinni::I32::toCpp(obj.exposure),
            ::djinni::I32::toCpp(obj.iso)};
}

auto VideoInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LPAVideoInfo alloc] initWithInterval:(::djinni::F32::fromCpp(cpp.interval))
                                              fps:(::djinni::I32::fromCpp(cpp.fps))
                                       resolution:(::djinni::I32::fromCpp(cpp.resolution))
                                         exposure:(::djinni::I32::fromCpp(cpp.exposure))
                                              iso:(::djinni::I32::fromCpp(cpp.iso))];
}

}  // namespace djinni_generated
