// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import <Foundation/Foundation.h>

@interface LPAVideoInfo : NSObject
- (nonnull instancetype)initWithInterval:(float)interval
                                     fps:(int32_t)fps
                              resolution:(int32_t)resolution
                                exposure:(int32_t)exposure
                                     iso:(int32_t)iso;
+ (nonnull instancetype)videoInfoWithInterval:(float)interval
                                          fps:(int32_t)fps
                                   resolution:(int32_t)resolution
                                     exposure:(int32_t)exposure
                                          iso:(int32_t)iso;

@property (nonatomic, readonly) float interval;

@property (nonatomic, readonly) int32_t fps;

@property (nonatomic, readonly) int32_t resolution;

@property (nonatomic, readonly) int32_t exposure;

@property (nonatomic, readonly) int32_t iso;

@end
