// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#import "LPAVideoInfo.h"


@implementation LPAVideoInfo

- (nonnull instancetype)initWithInterval:(float)interval
                                     fps:(int32_t)fps
                              resolution:(int32_t)resolution
                                exposure:(int32_t)exposure
                                     iso:(int32_t)iso
{
    if (self = [super init]) {
        _interval = interval;
        _fps = fps;
        _resolution = resolution;
        _exposure = exposure;
        _iso = iso;
    }
    return self;
}

+ (nonnull instancetype)videoInfoWithInterval:(float)interval
                                          fps:(int32_t)fps
                                   resolution:(int32_t)resolution
                                     exposure:(int32_t)exposure
                                          iso:(int32_t)iso
{
    return [[self alloc] initWithInterval:interval
                                      fps:fps
                               resolution:resolution
                                 exposure:exposure
                                      iso:iso];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p interval:%@ fps:%@ resolution:%@ exposure:%@ iso:%@>", self.class, (void *)self, @(self.interval), @(self.fps), @(self.resolution), @(self.exposure), @(self.iso)];
}

@end
