// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public final class CaptureQuickMode {

    public static final String TRAFFIC_FLOW = "traffic_flow";

    public static final String WIND_SKY = "wind_sky";

    public static final String SUN_RISE_SET = "sun_rise_set";

    public static final String NO_WIND_SKY = "no_wind_sky";

    public static final String FLOWERS_BLOOM_FADE = "flowers_bloom_fade";

    public static final String DAY_TURN_NIGHT = "day_turn_night";


    public CaptureQuickMode(
            ) {
    }

    @Override
    public String toString() {
        return "CaptureQuickMode{" +
        "}";
    }

}
