// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public final class ConfigKeyValue {

    public static final String VIDEO_INTERVAL = "interval";

    public static final String VIDEO_INTERVAL_UNIT = "interval_unit";

    public static final String VIDEO_FPS = "fps";

    public static final String VIDEO_BITRATE = "video_bitrate";

    public static final String CAPTURE_MODE = "capture_mode";

    public static final String CAPTURE_MODE_VIDEO = "video";

    public static final String CAPTURE_MODE_PHOTO = "photo";

    public static final String CAPTURE_MODE_LINE = "capture_video_line";


    public ConfigKeyValue(
            ) {
    }

    @Override
    public String toString() {
        return "ConfigKeyValue{" +
        "}";
    }

}
