// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public final class ConfigKeyValue {

    public static final String CAPTURE_MODE = "capture_mode";

    public static final String CAPTURE_MODE_VIDEO = "video";

    public static final String CAPTURE_MODE_PHOTO = "photo";


    public ConfigKeyValue(
            ) {
    }

    @Override
    public String toString() {
        return "ConfigKeyValue{" +
        "}";
    }

}
