// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public final class ConstDefine {

    /** camera */
    public static final String FLASH = "flash";

    public static final String AUTO = "auto";

    public static final String STR_YES = "yes";

    public static final String STR_NO = "no";

    public static final String QUALITY = "quality";

    public static final String QUALITY_LOW = "low";

    public static final String QUALITY_MEDIUM = "medium";

    public static final String QUALITY_HIGH = "high";

    public static final String QUALITY_PHOTO = "photo";

    public static final String CAMERA_POS = "camera_pos";

    public static final String CAMERA_POS_FRONT = "front";

    public static final String CAMERA_POS_BACK = "back";

    public static final String EXPOSURE = "exposure";

    public static final String MANUAL = "manual";

    public static final String POINT = "point";

    public static final String EXPOSURE_X = "exposure_x";

    public static final String EXPOSURE_Y = "exposure_y";

    public static final String EXPOSURE_LEV = "exposure_lev";

    public static final String ISO = "iso";

    public static final String FOCUS = "focus";

    public static final String FOCUS_RANGE = "focus_range";

    public static final String LOCK = "lock";

    /**video */
    public static final String INTERVAL = "interval";

    public static final String RESOLUTION = "resolution";

    public static final String FPS = "fps";

    public static final String BITRATE = "bitrate";


    public ConstDefine(
            ) {
    }

    @Override
    public String toString() {
        return "ConstDefine{" +
        "}";
    }

}
