// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public abstract class LapseSettingUiGen {
    public abstract void initializeSliberFps(int min, int max);

    public abstract void initializeSliberLapse(int min, int max);

    public abstract void updateFps(int fps);

    public abstract void updateLapse(int lapse);

    public abstract void updatePicker(int index);
}
