// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public abstract class LapseSettingDlgDelegate {
    public abstract void updateSegMode(IntervalMode mode);

    public abstract void updateFps(int fps);

    public abstract void updateLapse(float lapse);

    public abstract int getFps();

    public abstract float getLapse();
}
