// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public enum LapseEvent {
    NONE,
    CAMERA_BTN_CAPTURE,
    CAMERA_BTN_PAUSE,
    CAMERA_BTN_STOP,
    CAMERA_BTN_RESUME,
    CAMERA_BTN_LAPSE,
    CAMERA_BTN_RATIO,
    CAMERA_BTN_MORE,
    CAMERA_BTN_LIBRARY,
    CAMERA_BTN_SWITCH,
    MAX,
    ;
}
