// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class LogicGen {
    public abstract boolean initialize(String config);

    public abstract String getProjectsPath();

    public abstract void captureStart();

    public abstract void capturePause();

    public abstract void captureResume();

    public abstract void captureStop();

    public abstract void lapseStop();

    public abstract void lapseResume();

    public static native LogicGen instance();

    private static final class CppProxy extends LogicGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean initialize(String config)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_initialize(this.nativeRef, config);
        }
        private native boolean native_initialize(long _nativeRef, String config);

        @Override
        public String getProjectsPath()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getProjectsPath(this.nativeRef);
        }
        private native String native_getProjectsPath(long _nativeRef);

        @Override
        public void captureStart()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_captureStart(this.nativeRef);
        }
        private native void native_captureStart(long _nativeRef);

        @Override
        public void capturePause()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_capturePause(this.nativeRef);
        }
        private native void native_capturePause(long _nativeRef);

        @Override
        public void captureResume()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_captureResume(this.nativeRef);
        }
        private native void native_captureResume(long _nativeRef);

        @Override
        public void captureStop()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_captureStop(this.nativeRef);
        }
        private native void native_captureStop(long _nativeRef);

        @Override
        public void lapseStop()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_lapseStop(this.nativeRef);
        }
        private native void native_lapseStop(long _nativeRef);

        @Override
        public void lapseResume()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_lapseResume(this.nativeRef);
        }
        private native void native_lapseResume(long _nativeRef);
    }
}
