// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class LogicGen {
    public abstract boolean initialize(String config);

    public abstract String getProjectsPath();

    public static native LogicGen instance();

    private static final class CppProxy extends LogicGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean initialize(String config)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_initialize(this.nativeRef, config);
        }
        private native boolean native_initialize(long _nativeRef, String config);

        @Override
        public String getProjectsPath()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getProjectsPath(this.nativeRef);
        }
        private native String native_getProjectsPath(long _nativeRef);
    }
}
