// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public enum PublishChannel {
    NONE,
    FACEBOOK,
    YOUTUBE,
    MIAOPAI,
    YOUKU,
    ;
}
