// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class QuickModeGen {
    public abstract String getName();

    public abstract int getFps();

    public abstract int getInterval();

    public static native QuickModeGen create(String name, int fps, int interval);

    private static final class CppProxy extends QuickModeGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getName()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getName(this.nativeRef);
        }
        private native String native_getName(long _nativeRef);

        @Override
        public int getFps()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getFps(this.nativeRef);
        }
        private native int native_getFps(long _nativeRef);

        @Override
        public int getInterval()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getInterval(this.nativeRef);
        }
        private native int native_getInterval(long _nativeRef);
    }
}
