// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

package dyno.fun.lapse;

public final class VideoInfo {


    /*package*/ final float mInterval;

    /*package*/ final int mFps;

    /*package*/ final int mResolution;

    /*package*/ final int mExposure;

    /*package*/ final int mIso;

    public VideoInfo(
            float interval,
            int fps,
            int resolution,
            int exposure,
            int iso) {
        this.mInterval = interval;
        this.mFps = fps;
        this.mResolution = resolution;
        this.mExposure = exposure;
        this.mIso = iso;
    }

    public float getInterval() {
        return mInterval;
    }

    public int getFps() {
        return mFps;
    }

    public int getResolution() {
        return mResolution;
    }

    public int getExposure() {
        return mExposure;
    }

    public int getIso() {
        return mIso;
    }

    @Override
    public String toString() {
        return "VideoInfo{" +
                "mInterval=" + mInterval +
                "," + "mFps=" + mFps +
                "," + "mResolution=" + mResolution +
                "," + "mExposure=" + mExposure +
                "," + "mIso=" + mIso +
        "}";
    }

}
