// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "capture_quick_mode.hpp"  // my header

namespace lpase {

std::string const CaptureQuickMode::TRAFFIC_FLOW = {"traffic_flow"};

std::string const CaptureQuickMode::WIND_SKY = {"wind_sky"};

std::string const CaptureQuickMode::SUN_RISE_SET = {"sun_rise_set"};

std::string const CaptureQuickMode::NO_WIND_SKY = {"no_wind_sky"};

std::string const CaptureQuickMode::FLOWERS_BLOOM_FADE = {"flowers_bloom_fade"};

std::string const CaptureQuickMode::DAY_TURN_NIGHT = {"day_turn_night"};

}  // namespace lpase
