// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <string>
#include <utility>

namespace lpase {

struct CaptureQuickMode final {

    static std::string const TRAFFIC_FLOW;

    static std::string const WIND_SKY;

    static std::string const SUN_RISE_SET;

    static std::string const NO_WIND_SKY;

    static std::string const FLOWERS_BLOOM_FADE;

    static std::string const DAY_TURN_NIGHT;
};

}  // namespace lpase
