// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <string>
#include <utility>

namespace lpase {

struct ConfigKeyValue final {

    static std::string const CAPTURE_MODE;

    static std::string const CAPTURE_MODE_VIDEO;

    static std::string const CAPTURE_MODE_PHOTO;
};

}  // namespace lpase
