// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "config_key_value.hpp"  // my header

namespace lpase {

std::string const ConfigKeyValue::CAPTURE_MODE = {"capture_mode"};

std::string const ConfigKeyValue::CAPTURE_MODE_VIDEO = {"video"};

std::string const ConfigKeyValue::CAPTURE_MODE_PHOTO = {"photo"};

}  // namespace lpase
