// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <string>
#include <utility>

namespace lpase {

struct ConstDefine final {

    /** camera */
    static std::string const FLASH;

    static std::string const AUTO;

    static std::string const STR_YES;

    static std::string const STR_NO;

    static std::string const QUALITY;

    static std::string const QUALITY_LOW;

    static std::string const QUALITY_MEDIUM;

    static std::string const QUALITY_HIGH;

    static std::string const QUALITY_PHOTO;

    static std::string const CAMERA_POS;

    static std::string const CAMERA_POS_FRONT;

    static std::string const CAMERA_POS_BACK;

    static std::string const EXPOSURE;

    static std::string const MANUAL;

    static std::string const POINT;

    static std::string const EXPOSURE_X;

    static std::string const EXPOSURE_Y;

    static std::string const EXPOSURE_LEV;

    static std::string const ISO;

    static std::string const FOCUS;

    static std::string const FOCUS_RANGE;

    static std::string const LOCK;

    /**video */
    static std::string const INTERVAL;

    static std::string const RESOLUTION;

    static std::string const FPS;

    static std::string const BITRATE;
};

}  // namespace lpase
