// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#include "const_define.hpp"  // my header

namespace lpase {

std::string const ConstDefine::FLASH = {"flash"};

std::string const ConstDefine::AUTO = {"auto"};

std::string const ConstDefine::STR_YES = {"yes"};

std::string const ConstDefine::STR_NO = {"no"};

std::string const ConstDefine::QUALITY = {"quality"};

std::string const ConstDefine::QUALITY_LOW = {"low"};

std::string const ConstDefine::QUALITY_MEDIUM = {"medium"};

std::string const ConstDefine::QUALITY_HIGH = {"high"};

std::string const ConstDefine::QUALITY_PHOTO = {"photo"};

std::string const ConstDefine::CAMERA_POS = {"camera_pos"};

std::string const ConstDefine::CAMERA_POS_FRONT = {"front"};

std::string const ConstDefine::CAMERA_POS_BACK = {"back"};

std::string const ConstDefine::EXPOSURE = {"exposure"};

std::string const ConstDefine::MANUAL = {"manual"};

std::string const ConstDefine::POINT = {"point"};

std::string const ConstDefine::EXPOSURE_X = {"exposure_x"};

std::string const ConstDefine::EXPOSURE_Y = {"exposure_y"};

std::string const ConstDefine::EXPOSURE_LEV = {"exposure_lev"};

std::string const ConstDefine::ISO = {"iso"};

std::string const ConstDefine::FOCUS = {"focus"};

std::string const ConstDefine::FOCUS_RANGE = {"focus_range"};

std::string const ConstDefine::LOCK = {"lock"};

std::string const ConstDefine::INTERVAL = {"interval"};

std::string const ConstDefine::RESOLUTION = {"resolution"};

std::string const ConstDefine::FPS = {"fps"};

std::string const ConstDefine::BITRATE = {"bitrate"};

}  // namespace lpase
