// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace lpase {

class DataGen {
public:
    virtual ~DataGen() {}

    static std::shared_ptr<DataGen> instance();

    virtual bool initialize(const std::string & config) = 0;

    virtual std::string getProjectsDir() = 0;

    virtual std::string getCaptureMode() = 0;

    virtual void setCaptureMode(const std::string & mode) = 0;

    virtual int32_t getCaptureIntevalMillsec() = 0;

    virtual int32_t getCaptureInteval() = 0;

    virtual std::string getCaptureIntevalUnit() = 0;

    virtual void setCaptureInteval(int32_t value, const std::string & unit) = 0;

    virtual void setCaptureIntervalQuickMode(const std::string & mode) = 0;

    virtual std::string getCaptureIntervalQuickMode() = 0;

    virtual int32_t getFps() = 0;

    virtual int32_t getBitrate() = 0;

    virtual int32_t getResolution() = 0;

    virtual void setFps(int32_t fps) = 0;

    virtual void setBitrate(int32_t bitrate) = 0;

    virtual void setResolution(int32_t reso) = 0;
};

}  // namespace lpase
