// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>

namespace lpase {

class LapseSettingUiGen {
public:
    virtual ~LapseSettingUiGen() {}

    virtual void initializeSliberFps(int32_t min, int32_t max) = 0;

    virtual void initializeSliberLapse(int32_t min, int32_t max) = 0;

    virtual void updateFps(int32_t fps) = 0;

    virtual void updateLapse(int32_t lapse) = 0;

    virtual void updatePicker(int32_t index) = 0;
};

}  // namespace lpase
