// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace lpase {

class LapseSettingDlgDelegate;
enum class IntervalMode;

class LapseSettingDlgGen {
public:
    virtual ~LapseSettingDlgGen() {}

    static std::shared_ptr<LapseSettingDlgGen> instance();

    virtual void onLoad(const std::shared_ptr<LapseSettingDlgDelegate> & delegate) = 0;

    virtual void onShow() = 0;

    virtual bool onFpsChange(int32_t fps) = 0;

    virtual bool onLapseChange(IntervalMode mode, float lapse) = 0;

    virtual void onSelectInterval(IntervalMode mode) = 0;

    virtual bool onSave(int32_t fps, float lapse, IntervalMode mode) = 0;
};

}  // namespace lpase
