// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>

namespace lpase {

enum class IntervalMode;

class LapseSettingDlgDelegate {
public:
    virtual ~LapseSettingDlgDelegate() {}

    virtual void updateSegMode(IntervalMode mode) = 0;

    virtual void updateFps(int32_t fps) = 0;

    virtual void updateLapse(float lapse) = 0;

    virtual int32_t getFps() = 0;

    virtual float getLapse() = 0;
};

}  // namespace lpase
