// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <functional>

namespace lpase {

enum class LapseUiScene : int {
    CAMERA,
    LIBRARY,
};

}  // namespace lpase

namespace std {

template <>
struct hash<::lpase::LapseUiScene> {
    size_t operator()(::lpase::LapseUiScene type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
