// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <memory>
#include <string>

namespace lpase {

class LogicGen {
public:
    virtual ~LogicGen() {}

    static std::shared_ptr<LogicGen> instance();

    virtual bool initialize(const std::string & config) = 0;

    virtual std::string getProjectsPath() = 0;
};

}  // namespace lpase
