// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <memory>
#include <string>

namespace lpase {

class MoiveInfoGen;

class MoiveInfoManagerGen {
public:
    virtual ~MoiveInfoManagerGen() {}

    static std::shared_ptr<MoiveInfoManagerGen> instance();

    virtual bool initialize(const std::string & config) = 0;

    virtual std::shared_ptr<MoiveInfoGen> createMoiveInfo(const std::string & path) = 0;

    virtual std::shared_ptr<MoiveInfoGen> findMoiveInfo(const std::string & name) = 0;

    virtual void removeMoiveInfo(const std::string & name) = 0;

    virtual void save() = 0;
};

}  // namespace lpase
