// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>
#include <string>

namespace lpase {

class MoiveInfoGen {
public:
    virtual ~MoiveInfoGen() {}

    virtual std::string getName() = 0;

    virtual int32_t getFrameAmount() = 0;

    virtual float getDurationSecond() = 0;

    virtual float getFPS() = 0;

    virtual float getRecordLapse() = 0;

    virtual float getRecordDuration() = 0;

    virtual bool setName(const std::string & name) = 0;

    virtual void setFrameAmount(int32_t amount) = 0;

    virtual void setDurationSecond(float seconds) = 0;

    virtual void setFPS(float fps) = 0;

    virtual void setRecordDuration(float duration) = 0;

    virtual void setRecordLapse(float lapse) = 0;
};

}  // namespace lpase
