// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace lpase {

class ProjectCellGen {
public:
    virtual ~ProjectCellGen() {}

    static std::shared_ptr<ProjectCellGen> create(const std::string & path, int32_t out_w, int32_t out_h);

    virtual std::string getPath() = 0;

    virtual std::string getName() = 0;

    virtual std::string getCreateTime() = 0;

    virtual std::string getLength() = 0;

    virtual std::string getFps() = 0;

    virtual std::string getRecordDuration() = 0;
};

}  // namespace lpase
