// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <functional>

namespace lpase {

enum class PublishChannel : int {
    NONE,
    FACEBOOK,
    YOUTUBE,
    MIAOPAI,
    YOUKU,
};

}  // namespace lpase

namespace std {

template <>
struct hash<::lpase::PublishChannel> {
    size_t operator()(::lpase::PublishChannel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
