// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lapse.djinni

#pragma once

#include <memory>

namespace lpase {

enum class LapseUiScene;

class UilogicGen {
public:
    virtual ~UilogicGen() {}

    static std::shared_ptr<UilogicGen> instance();

    virtual bool initialize(LapseUiScene scene) = 0;
};

}  // namespace lpase
